### PR TITLE
Remove the "Golden Signals" dashboard.

### PR DESCRIPTION
**Pull request by dazoakley**
This has been replaced by a single dashboard deployed centrally from the
`monitoring` namespace.

https://grafana.live.cloud-platform.service.justice.gov.uk/d/golden-signals

This will remove a lot of noise from the grafana dashboards list.

### CODE REVIEW

**Comment by swilson-mojhub** [comment]
@dazoakley .. just checking the impact of this PR, will it remove anything from existing team Grafana dashboards?

**Comment by dazoakley** [comment]
@swilson-mojhub It will remove the individual "<namespace> / <service> / Golden Signals" dashboard from grafana, but they can get the same information (with correct/fixed graphs) from the central dashboard (https://grafana.live.cloud-platform.service.justice.gov.uk/d/golden-signals).

**Review by mxco86 — COMMENTED** [review]
This is a big improvement - do we need to check if any teams have processes based on the old dashboard location before merging?

**Review by swilson-mojhub — APPROVED** [review]
We've put out multiple coms to raise awareness. 

The PR makes dashboards easier to consume.

**Pull request merged**
